### ISSUE TITLE
투자금 입력 텍스트 필드 개선(리젝 당함)

### ISSUE THREAD

**Issue by HJEHA** [Team-Nogari/Huhoe#61]
텍스트 필드 위에 레이블 올려서 텍스트 필드를 커스텀으로 구현함.
앱 심사 시 커서 안보임, 숫자 외 다른 텍스트가 입력될 경우 콘텐츠 안보임 등 문제 발생함.

**Comment by yim2627** [comment]
좀 해줘요 좀
