### ISSUE TITLE
도움말 화면 페이지 컨트롤 개선

### ISSUE THREAD

**Issue by HJEHA** [Team-Nogari/Huhoe#62]
다음 버튼 눌렀을 때 페이지 컨트롤 인덱스 안바뀜.

**Comment by yim2627** [comment]
리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!리젝 그만해!!!!!!!!!!!!!!!!!!!!!!!!!!!!
