### ISSUE TITLE
상세화면 성능 개선

### ISSUE THREAD

**Issue by yim2627** [Team-Nogari/Huhoe#66]
Input(투자 금액 입력)이 들어왔을 때 코인들의 가격을 API를 통해 가져온 뒤 맵핑하는 과정에서 성능 저하가 발생함

**Comment by HJEHA** [comment]
기존 방식
1. canstick Entity -> Domain 맵핑 과정 중 날짜를 TimeInterval로 변환함.
2. 상세화면에서 인풋(투자금)이 입력되면 과거 날짜를 비교하는 과정에서 TimeInterval -> String -> TimeInterval로 여러번 맵핑해야하는 문제가 발생함. 과거 데이터가 많은 코인일수록 성능저하 발생

개선 방식
1. canstick Entity -> Domain 맵핑 과정 중 날짜를 String(2022.04.05)로 변환함.
2. 상세화면에서 인풋(투자금)이 입력되면 과거 날짜를 비교하는 과정을 개선하여 성능저하를 개선함.
